name: Build and Release DLL with MinGW-w64 GCC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MinGW-w64 GCC
        run: |
          choco install mingw -y
      
      - name: Build DLL
        run: gcc -shared -o pcinfo.dll src/pcinfo.c
      - name: Upload DLL
        uses: actions/upload-artifact@v2
        with:
          name: pcinfo
          path: pcinfo.dll

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download DLL
        uses: actions/download-artifact@v2
        with:
          name: pcinfo

      - name: Get or create release
        id: get_release
        run: |
          RELEASE_ID=$(curl --silent "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/${{ github.ref_name }}" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq '.id')
          UPLOAD_URL=$(curl --silent "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/${{ github.ref_name }}" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq '.upload_url')
          if [ "$RELEASE_ID" == "null" ]; then
            RELEASE_RESPONSE=$(curl --silent -X POST "https://api.github.com/repos/$GITHUB_REPOSITORY/releases" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -d '{
                "tag_name": "${{ github.ref_name }}",
                "target_commitish": "main",
                "name": "Release ${{ github.ref_name }}",
                "body": "Release ${{ github.ref_name }}",
                "draft": false,
                "prerelease": false
              }')
            RELEASE_ID=$(echo "$RELEASE_RESPONSE" | jq '.id')
            UPLOAD_URL=$(echo "$RELEASE_RESPONSE" | jq '.upload_url')
          fi
          echo "::set-output name=release_id::$RELEASE_ID"
          echo "::set-output name=upload_url::$UPLOAD_URL"

      - name: Upload DLL
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./pcinfo.dll
          asset_name: pcinfo.dll
          asset_content_type: application/octet-stream