name: PCINFO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MinGW-w64 GCC
        run: |
          choco install mingw -y
      
      - name: Build DLL
        run: gcc -shared -o pcinfo.dll src/pcinfo.c
      - name: Upload DLL
        uses: actions/upload-artifact@v2
        with:
          name: pcinfo
          path: pcinfo.dll

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download DLL
        uses: actions/download-artifact@v2
        with:
          name: pcinfo

      - name: Delete old release and tag
        run: |
          RELEASE_ID=$(curl --silent "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/${{ github.ref_name }}" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq '.id')
          if [ "$RELEASE_ID" != "null" ]; then
            curl -X DELETE "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/$RELEASE_ID" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
            curl -X DELETE "https://api.github.com/repos/$GITHUB_REPOSITORY/git/refs/tags/${{ github.ref_name }}" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload DLL
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pcinfo.dll
          asset_name: pcinfo.dll
          asset_content_type: application/octet-stream